name: bookdown

on:
  push:
     branches:
       - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install bookdown
        run: Rscript -e "install.packages('bookdown')"
      - name: Build book
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: Bookdown
          path: Bookdown
